### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bmkimagem** [termijn/dicom-viewer#2]
I have this error when compiling. Do you have any tips on how to solve it? 

'vtkSimpleImageToImageFilter.h': No such file or directory	RenderEngine

**Comment by termijn** [comment]
Hi,

I will have to check later. My initial guess would be that there is no vtk
installed. Did you do this step as documented in the Readme:


*Install VTK toolkit and set VTK_PATH environment variable to installed
location (e.g. VTK_PATH=C:\Program Files\VTK).*


Regards
Martijn

Op ma 6 sep. 2021 02:51 schreef bmkimagem ***@***.***>:

**Comment by bmkimagem** [comment]
Yes, I did. Only if the VTK library I downloaded is wrong. In your project you don't have the address of the one used. The compiled version worked very well. I was going to try to make adjustments. I found this viewer very good, congratulations.

**Comment by termijn** [comment]
Ahh indeed I didn't mention the version. Thanks. Just out of curiosity..
what are you using it for?


Martijn

Op ma 6 sep. 2021 22:00 schreef bmkimagem ***@***.***>:

**Comment by bmkimagem** [comment]
I'm studying the MPR part. I like how it was done here.

**Comment by bmkimagem** [comment]
I couldn't get the code to work, at least I tried.

**Comment by termijn** [comment]
If you have a feature request, feel free to let me know 😁.

Op ma 6 sep. 2021 22:35 schreef bmkimagem ***@***.***>:
